### ISSUE TITLE
Get Swole!

### ISSUE THREAD

**Issue by benjinchang** [benjinchang/P1-Swolemate#2]
No time to waste!
We have to get swole now!

**Comment by danielfyeh** [comment]
just did biceps today. You know curls for the girls right?

**Comment by sharloteean** [comment]
![gainz](https://cloud.githubusercontent.com/assets/9024193/24025761/ba88055a-0a79-11e7-91c6-632eed59605c.jpg)

**Comment by benjinchang** [comment]
Thanks for your commitment to getting swole.
